listeners:
  - address: 0.0.0.0:8080
    cluster: tcpproxy
clusters:
  - name: tcpproxy
    endpoints:
    - 159.138.131.32:8080
    tls: client
tls:
  - name: client
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    key: ./crt/server.pem
    cert: ./crt/server.crt
