listeners:
  - address: 0.0.0.0:8080
    cluster: tcpproxy
clusters:
  - name: tcpproxy
    endpoints:
    - proxy.lixiangyun.top:8080
    - proxy.lixiangyun.top:8081
    - proxy.lixiangyun.top:8082
    tls: client
tls:
  - name: client
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    key: ./crt/server.pem
    cert: ./crt/server.crt
