listeners:
  - address: 0.0.0.0:8080
    cluster: goproxy_basic
    tls: server
clusters:
  - name: goproxy_basic
    endpoints:
    - 127.0.0.1:1000
tls:
  - name: client
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server
    key: ./crt/server.pem
    cert: ./crt/server.crt
