FROM golang:1.8.1

WORKDIR /usr1/golang/src
ENV GOPATH=/usr1/golang/src
ENV GOOS=linux
ENV CGO_ENABLED=0

RUN go get -u -v github.com/lixiangyun/goproxy/

WORKDIR /usr1/golang/src/github.com/lixiangyun/goproxy/examples/goproxy-basic/

RUN go build .

RUN ls -il

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

RUN cp -rf /usr1/golang/src/github.com/lixiangyun/goproxy/examples/goproxy-basic/goproxy-basic ./proxy

RUN chmod +x *

EXPOSE 8080

# docker build -t goproxy:1.0 .
# docker run -d -p 8080:8080 --restart=always goproxy:1.0

ENTRYPOINT ["./proxy", "addr", "8080"]
